name: Robot Lam Sach Du Lieu
on:
  schedule:
    - cron: "0 21 * * *" # Tự động chạy lúc 4h sáng VN hàng ngày
  push:
    paths:
      - 'raw_data/*.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Chạy Robot dọn dẹp
        run: python robot_clean.py
          
      - name: Luu lai du lieu sạch
        run: |
          git config --global user.name 'Robot-Affiliate'
          git config --global user.email 'robot@affiliate.com'
          git add processed_data/*.csv
          git commit -m "Robot đã dọn dẹp dữ liệu ngày $(date +%F)" || exit 0
          git push
