name: Robot_Tu_Dong_Lay_Hang

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write # Đây là dòng cực kỳ quan trọng để sửa lỗi X đỏ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cai dat Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Cai dat thu vien
        run: pip install pandas openpyxl
      - name: Chay Robot
        run: python crawler.py
      - name: Luu ket qua
        run: |
          git config --global user.name "Robot-Nam-Nguyen"
          git config --global user.email "bot@github.com"
          git add database.csv
          git commit -m "Robot cap nhat database.csv" || echo "No changes"
          git push
