name: Robot_He_Thong_Lixi_Va_Crawler

on:
  schedule:
    - cron: '0 0 * * *' # Tự động chạy lúc 7h sáng giờ VN
  workflow_dispatch: # Cho phép bấm chạy tay bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run Robot Crawler
        run: python crawler.py

      - name: Run Tiem Li Xi
        run: python run.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Robot-Nam-Nguyen"
          git config --global user.email "robot@github.com"
          
          # QUAN TRỌNG: Cập nhật đường dẫn file đúng cấu trúc mới
          git add index.html database.csv database10.csv database6.csv
          git add data/history.csv data/friends.csv data/products.csv
          
          git commit -m "Robot: Cap nhat lich su va index.html" || exit 0
          git push
