name: Robot Cuu Van Tu Dong

on:
  schedule:
    # 1h, 5h, 12h giờ Quốc tế tương ứng 8h, 12h, 19h Việt Nam
    - cron: '0 1,5,12 * * *'
  workflow_dispatch: # Giúp bạn bấm chạy thủ công trên điện thoại bất cứ lúc nào

jobs:
  run-robot:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code ve
        uses: actions/checkout@v3

      - name: Chay Python Robot
        run: |
          python engine/story_engine.py 
          # Tôi thấy bạn có file story_engine.py trong ảnh, ta sẽ dùng nó làm bộ não chính

      - name: Day ket qua len Github
        run: |
          git config --global user.name "Robot-Cua-Hang"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Robot da cap nhat link va don dep file HTML" || exit 0
          git push
